plots:
  - Accuracy:
      x: step
      y:
        training/plots/metrics/acc_train.tsv: acc_train
        training/plots/metrics/acc_test.tsv: acc_test
      y_label: accuracy
  - Loss:
      x: step
      y:
        training/plots/metrics/loss_train.tsv: loss_train
        training/plots/metrics/loss_test.tsv: loss_test
      y_label: loss
  - Confusion matrix:
      template: confusion
      x: actual
      y:
        training/plots/sklearn/confusion_matrix.json: predicted
  - Actual vs Predicted:
      template: jitter.json
      x: actual
      y:
        training/plots/sklearn/confusion_matrix.json: predicted
  - hist.csv:
      x: preds
      y: digit
      template: bar_horizontal
      title: Histogram of Predictions
  - training/plots/images
stages:
  train:
    cmd: python train.py
    deps:
      - data/MNIST
      - train.py
    params:
      - params.yaml:
    outs:
      - model.pt:
          checkpoint: true
      - training/plots:
          persist: true
      - hist.csv
    metrics:
      - training/metrics.json:
          persist: true
          cache: false
