plots:
  - acc_v_loss:
      x: step
      y:
        training/plots/metrics/acc.tsv: acc
        training/plots/metrics/loss.tsv: loss
  - training/plots/images
  - training/plots/sklearn/confusion_matrix.json:
      template: confusion
      x: actual
      y: predicted
stages:
  train:
    cmd: python train.py
    deps:
      - data/MNIST
      - train.py
    params:
      - params.yaml:
    outs:
      - model.pt:
          checkpoint: true
      - training/plots:
          persist: true
    metrics:
      - training/metrics.json:
          persist: true
          cache: false
